backend:
  name: github
  repo: z08id-coder/bio
  branch: main
  # هاد السطر هو اللي رح يحل المشكلة، ممنوع يكون قبله api.netlify
  auth_endpoint: https://static-cms-auth.vercel.app/api/auth
  app_id: "3234424"
  app_secret: "3fd7294d13874456b5c3435682dde76a46ed6f2d"

media_folder: "images"
public_folder: "images"

collections:
  - name: "posts"
    label: "البوستات"
    folder: "_posts"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}"
    fields:
      - {label: "اسم الشخص", name: "title", widget: "string"}
      - {label: "التاريخ", name: "date", widget: "hidden", default: "{{now}}"}
      - {label: "الأفاتار (صورة الشخص)", name: "avatar", widget: "image", required: true}
      - {label: "صورة البوست (اختياري)", name: "image", widget: "image", required: false}
      - {label: "نص المنشور", name: "body", widget: "markdown"}
